
server:
  port: 0
  ssl:
    key-store-password: changeit
    key-store: classes/security.p12
    key-store-type: PKCS12
spring:
  multipart:
    maxFileSize: 51200KB
    maxRequestFile: 51200KB
  datasource:
    url: jdbc:postgresql://${domain}:5432/inquisitve
    password: password
    username: keycloak
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        search:
          backend:
            analysis:
              configurer: com.smilebat.learntribe.dataaccess.config.CustomLuceneAnalysisConfigurer
            protocol: http
            directory:
              root: /data/index/default
    show-sql: true
  security:
    require-ssl: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${feign.client.url.keycloak}/realms/master

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    serviceUrl:
#      defaultZone: http://${domain}:8761/eureka

feign:
  client:
    url:
      keycloak: http://${domain}
    config:
      default:
        loggerLevel: full
logging:
  level:
    com:
      smilebat:
        learntribe:
          learntribeclients: DEBUG


domain: www.smilebat.xyz

#domain: localhost:8085/auth


